### ISSUE TITLE
Copy colors from the touch bar

### ISSUE THREAD

**Issue by superhighfives** [superhighfives/pika#14]
One great way (among others) to propose color copy could be the Touch Bar, like [Contrast](https://contrasteapp.com) does:

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/9340937/104819837-9d8efb80-5830-11eb-931e-e1b6af3626ba.png">

_Originally posted by @meduzen in https://github.com/superhighfives/pika/issues/3#issuecomment-761611495_

**Comment by meduzen** [comment]
I’ve just downloaded 0.0.9-beta1, the shortcut works really well. Many thanks for that feature. 👍

I’m just not sure about the relevancy of the nice animation shown on the Touch Bar when going in the settings.
![image](https://user-images.githubusercontent.com/9340937/107161853-bc039500-699f-11eb-963d-152ac9dee592.png)

I think it’s a nice touch of detail (even if not useful), but it just instantaneously burned my eyes because I’m in dark mode, it’s midnight, and all lights are off at home. :D

Do not make decision on my single feedback (+ we don’t spend our lives in app settings), but for me:
- it’s okay if I’m in light mode (I turn it on during daylight);
- it could be darker in dark mode, or have a setting to be disabled.

**Comment by superhighfives** [comment]
Thanks so much for checking it out, and for the feedback, @meduzen.

Yeah, I originally had it just in the splash, and then was trying it out on other screens, but does feel a little intense and irrelevant. Having it in the splash makes sense to me because it ties the touchbar to the visualisation there, which it doesn't do for the other screens. Thinking I'll simplify it to be just for the splash.

Also, love the idea of lowering the brightness when dark mode is enabled, too. Will look into that.

🙌

**Comment by superhighfives** [comment]
Found a couple of other little issues, so going to pull the beta for now and resolve, as I hadn't pushed it out, and you are officially the only download @meduzen. 😊  Thanks again for flagging.

**Comment by superhighfives** [comment]
Shipped with https://github.com/superhighfives/pika/releases/tag/0.0.9 🎉
