### ISSUE TITLE
Automatically open in color-picking mode; probably foreground

### ISSUE THREAD

**Issue by bikrrr** [superhighfives/pika#20]
**Is your feature request related to a problem? Please describe.**
When I open **Pika** it's usually because I immediately want to select a color (to check accessibility). It would save me a click (or keypress) if it opened in color-picking mode. 

**Describe the solution you'd like**
If **Pika** is not "open", I'd like **Pika** to open and be in color-picking mode, probably foreground. When checking the accessibility of two colors, I usually start with foreground so that's _my_ preference; not sure if everyone would agree. 🤔

I really can't think of a scenario where I'd open Pika and NOT want to _immediately_ select a color. And since **Esc** exits that mode, it's pretty easy to cancel if one doesn't want that. Seems like making this default behavior would be cleaner than adding yet another setting.

**Describe alternatives you've considered**
I could use the new shortcut (thanks! 🙏) which is faster than clicking the eyedropper, but it's still an extra step. 

**Additional context**
I may be biased from having used MacOS's **Digital Color Picker**, which is _always_ in color-picking mode.

**Comment by superhighfives** [comment]
Hey @bikrrr—thanks for sharing. Been thinking about this one, and maybe it's a preference? Could be a checkbox in the general settings, like "Initialise color picker on toggle with global shortcut". Thinking it would default to foreground, as you say. 🤔

**Comment by bikrrr** [comment]
That'd be great _for me_, though I'd also want it to "auto-pick" _even when_ launched from the app icon or Spotlight.

The more important question is how often your overall customer base would prefer this behavior? If it's close to 50%, then adding a preference totally makes sense. 

But if there's likely to be a majority who want it one way vs the other (e.g., 80/20), then I'd avoid adding another setting. As a product designer, simplicity is one of my core design principles. I'm extremely deliberate when considering adding anything (feature, setting, etc.) to an existing design because I know from experience: 

1. Each additional element decreases usability ([Hick's Law](https://en.wikipedia.org/wiki/Hick%27s_law)).
2. Each addition increases complexity, both from a customer and supportability/testing perspective.
3. The likelihood of ever removing said addition, becomes near zero as the product is used by more and more people. 

In the ideal world—the one with lots of time and resources 😉—I'd recommend doing a few usability studies and/or instrumenting the product to find out _exactly_ what people do. Specifically, what percentage of launches do they _immediately_ pick a color vs. do something else?

A faster and more [lean approach](http://theleanstartup.com/principles) would be to just try the "auto-pick" behavior in a beta release, and see what feedback you get. If no one complains, then it was the right call; no need to add a preference. If more than a small minority doesn't like it, then add the setting. 

Sorry for the long reply; this is definitely a passion point for me. I've worked on too many products that were victims of teams not having the discipline to question every addition; resulting in a complicated mess that was impossible to simplify after the fact. 🙀

**Comment by bikrrr** [comment]
And yes, I did consider all of the above when I suggested the option to hide the menu bar icon. My thought is that people who want an icon vs. those who do not, would closer to a 50/50 split. My assumption is that there's a significant number of designers who rely on keyboard shortcuts AND also don't like clutter. ;)

**Comment by superhighfives** [comment]
Yeah, really well put @bikrrr. This is my first foray into app design outside the web, and it's definitely a brave new world, especially when it comes to usability and productivity. I think it was easier at the start to just-add-a-preference for everything, because they felt like pressing needs, but you're right that to continue like that after the core functionality of the app exists means that eventually preferences are super buried and difficult to navigate, testing is harder, edge cases increase, etc.

For now, I'm going to keep this open and see if it gets some more feedback / thumbs up, and leave it as an idea on the [project roadmap](https://github.com/superhighfives/pika/projects/1). Love the beta idea for testing out new ideas, too. Will keep that in mind.

Also, if anyone has thoughts on the above, I'm all ears.

**Comment by bikrrr** [comment]
Yeah, that totally makes sense. You definitely have more than an MVP here, so might as well be patient and see what kind of feedback you get. 

In the meantime, it's probably worth defining your product vision…if you haven't already: Who's the target audience? What user needs and goals do you plan to address? How will you differentiate from other similar apps?

A crisp product vision will help you evaluate feedback as it comes in; quickly deciding whether it aligns. And if not, then saying "no" and moving on. This is an important skill of good product managers, here are a couple references: 
- [Product strategy means saying no (Intercom blog)](https://www.intercom.com/blog/product-strategy-means-saying-no/)
- ["Focus is about saying no" — Steve Jobs (YouTube)](https://www.youtube.com/watch?v=0GD57UQg4X4)

**Comment by superhighfives** [comment]
Hey @bikrrr—appreciate the feedback, and the links. And I hear you on the product vision, too. This definitely started off as an experiment in the wasteland between Christmas and New Year, and I didn't expect it to grow as much as it has, so the original vision was pretty focused on:
a) getting something working, and
b) getting something working that I'd use

Will have a think about it, and start writing something up—at the very least, to make it easier to point to a document when people ask why it is the way it is. ☺️ 

Again, appreciate all the advice and feedback. 🙌

**Comment by superhighfives** [comment]
Awesome. Started a wiki to document things a little more clearly, @bikrrr: https://github.com/superhighfives/pika/wiki

**Comment by Clafouti** [comment]
Hi there!

Just wanted to drop a few words about this _enhancement_ request. I'm using [Sip](https://sipapp.io/) for about a year now, and I really like the fact that clicking the menu bar icon just opens the color picker. They also provide a way to check the contrast but it's hidden behind another click.

What I particularly like with Sip is that I can either click the menu bar on the left side (showing the color) to enter "picking mode" or I can click on the down arrow to display more _stuff_.

To me, it feels like the perfect balance between a setting I don't want to check (as a lazy user) and a "no-choice" solution.

Hopefully this post doesn't sound like "hey, look, another product is better than Pika". I actually prefer Pika's UX on the contrast checker, but I'd love to enter color-picking mode with a single click instead of two.

**Comment by superhighfives** [comment]
Hey @Clafouti—appreciate the feedback! You can currently right click Pika in the menu bar, so maybe it opens it in picking mode on left click, and right click has an option to view the app, which doesn't trigger the color picker. 🤔 At the moment I'm mainly focused on getting [v0.0.9](https://github.com/superhighfives/pika/milestone/2) ready for beta, but will keep this in mind for after that. 👍

**Comment by ovanbiervliet** [comment]
I'd also want it to directly go into color picking mode. Additionally, right clicking in my mind means secondary function, so that would be e.g. background color, not foreground color. 
I'm slowly getting used to typing 2 shortcuts for Pika to get a color reading, but I'd prefer 1. Perhaps I was too quick to agree on the foreground/background shortcuts being not system-wide? 😅 -because that would've solved it?

**Comment by superhighfives** [comment]
Hahaha, fair point! 😅 Having two global shortcuts for a colour picker feels like too much overhead to set / remember for a simple app, but could definitely try a beta where clicking Pika in the menu bar with the left mouse button opens with foreground picking initialised, and right clicking it opens with backgorund picking initialised. This would remove the status bar right-click menu, though, so that would be a potential drawback. Not sure how often that gets used, though.

It would also mean there's multiple different / inconsistent ways of accessing Pika—left click for foreground, right click for background, and show / hide shortcut. In reality that may not be too big an issue, but it's something to test in practice as it slightly bends my rule of having no unexpected / inconsistent side effects.

**Comment by ovanbiervliet** [comment]
Just to clarify regarding the menu icon: I don't think it should both pick fg on left and bg on right click. Right clicking the menu icon is often used to get the menu dropdown (when left is used for main action).

So there are a few possible ways we have available now, and most of them will probably be based on what app the user used before Pika (or just user preference)? E.g. I hide the dock and never use it, ever. I use Alfred to launch all apps because it is so much faster to type a few letters. If I visually interact with any running app it will be via the menu.

**Comment by superhighfives** [comment]
Okay, rad, testing our opening in foreground picking mode in `v0.0.10-beta1`—Pika now initialises color picking on the global shortcut / when showing the main window. You can try it out by checking "Subscribe to beta updates" in preferences and checking for updates. 👍

**Comment by ovanbiervliet** [comment]
I'm not convinced atm:

- First time: I use global hotkey and Pika is launched in picker mode with the window hidden (if that option is enabled)
- Subsequent times, when I'm in any other app, I need to use the global hotkey again to switch to Pika, and what happens then is that it disappears instead of activates.

The more I think about it, the more the global hotkey should not be linked to launching Pika itself: I set it to launch when the system starts, so why would I need a global hotkey then? To me, the global hotkey is to take a color reading from wherever I am. This may be different for others 🤷🏽

**Comment by superhighfives** [comment]
Yeah, I feel similarly, having spent some time with the beta. Going to try a slightly tweaked approach for `v0.0.10-beta2`. Keen to get feedback once it's out. Thanks @ovanbiervliet.

**Comment by superhighfives** [comment]
Okay, made a bunch of improvements here, so colour picking is triggered by the global shortcut, and only displays the window if a selection is made. The app can still be accessed via the menu bar / by opening it via Spotlight without it triggering the picker, and in my use so far I've found it far more intuitive. You can try it out in `v0.0.10-beta2` by checking "Subscribe to beta updates" in preferences and checking for updates. 🙌

**Comment by Clafouti** [comment]
I didn't have time to write a feedback on the `v0.0.10-beta1` but It'd have been quite the same as @ovanbiervliet's post.
Just tested the `v0.0.10-beta2` and it feels way more natural. I simply like it.

 I'm still not sure about having to click a button to paste the color I just picked, but hijacking the clipboard might not be the best solution (and that's also not related to this issue).

**Comment by superhighfives** [comment]
Thanks @Clafouti—really appreciate the feedback, and glad to hear `beta2` feels more natural.

On copying, you could potentially use ⌘C once you've picked to avoid needing to click anything in app. I get my global shortcut to ⌃⌥⌘C, so it feels a little more natural to move to the copying step.

**Comment by ovanbiervliet** [comment]
Much improved workflow I think, great work!

**Comment by superhighfives** [comment]
Great, this is merged in and will be released with `v0.0.10`. 👍
