### ISSUE TITLE
Poor contrast when hovering over text in menus

### ISSUE THREAD

**Issue by jsunsawyer** [superhighfives/pika#41]
![Screen Shot 2021-02-17 at 9 40 30 AM](https://user-images.githubusercontent.com/1007191/108245003-a9f2c680-7104-11eb-9b3a-f254f46b83fc.png)

**Comment by superhighfives** [comment]
Thanks for flagging @jsunsawyer—just to confirm, which version of macOS and which version of Pika are you on?

**Comment by jsunsawyer** [comment]
I'm using:

Pika: 0.0.8
Mac OS: 10.15.7

**Comment by superhighfives** [comment]
Thanks, @jsunsawyer. Weirdly I'm not getting this, and I'm on the same versions. I vaguely remember seeing something like this in early development, which I had fixed, so I'm curious what could be different between our setups.

Will keep this open in case anyone else comes across the same thing, or if you or anyone else has advice on reproducing it.

**Comment by jsunsawyer** [comment]
@superhighfives Ah, I know what you're missing here.

I have some Accessibility settings enabled for macOS.

Try enabling this setting:
Accessibility > Display > Reduce transparency

**Comment by superhighfives** [comment]
Ah, yep! Unfortunately it appears to be a macOS bug—it's present in 10.15, but is fixed in Big Sur. I tried to find a way around it at the time, but the underlying API is pretty bare bones, from memory. Cheers again for flagging, and for the additional detail. Will close, but if anyone is able to find a fix, I'd love to hear it. 👍

**Comment by jsunsawyer** [comment]
Ah bummer. Funny bug to exist in an a11y based app haha. Oh well.
