### ISSUE TITLE
Icon contrast too low

### ISSUE THREAD

**Issue by ovanbiervliet** [superhighfives/pika#43]
The contrast on the icons (settings, background color) is too low for accessibility reasons.

![Core-2021-0220 121822@2x](https://user-images.githubusercontent.com/3488544/108593793-14f70400-7376-11eb-9c60-5ed3d9c5ccbc.png)

Also happens with lighter background color:
![Core-2021-0220 122131@2x](https://user-images.githubusercontent.com/3488544/108593821-57204580-7376-11eb-9402-c8e195b643a7.png)

Edit: I saw this behaviour after first time usage. Now I get a dark cog for the settings, although the icon for background color remains nearly invisible.

**Comment by superhighfives** [comment]
Thanks for flagging, @ovanbiervliet. Just to clarify, which version of macOS is this on? Some of these are known bugs / quirks in SwiftUI, but the background colour menu icon is a new one. Also, do you have reduce transparency enabled in your accessibility settings?

**Comment by superhighfives** [comment]
Oh, also @ovanbiervliet, did you change between dark and light mode at all? That can also cause some quirks.

**Comment by ovanbiervliet** [comment]
Big Sur 11.2.1, no accessibility settings enabled.

Didn't change dark/light after installing. The cog fixed itself after I toggled the Hide Pika setting in the menu.

**Comment by ovanbiervliet** [comment]
Just did a quick test: from light to dark and back resulted in the cog being wrong again.

**Comment by superhighfives** [comment]
Yeah @ovanbiervliet, it's a bug in SwiftUI, essentially. Unfortunately I have no control over the display of the icons or their colours, which is why I've used shadows. This seems to only occur in Big Sur. From my experiments, I found:

- The cog / settings icon has a low opacity on launch. Once you interact with it, it changes to the appropriate colour. I've added some code to toggle it on and off quickly on appear, but it's a hack.  Changing from light to dark seems to make the icon permanently low opacity, and it doesn't always seem to work as expected. It's a frustrating one.
- You can't change the colour of the menu / (...) icons in the swatches, which is why they have a shadow, to try and make them more visible. Nothing I have tried has made the icon colour change, except for swapping between dark and light mode, so it seems to be baked in. The other option would be to place it inside a circle / some kind of background, similar to how the Swap button currently works. That's likely the best solution, but impacts the swatch design.

I'm still unsure how the background icon has a lower opacity there, as I can't recreate it. If you restart the app, is it still lower opacity?

Ultimately I'm keen to see if newer versions of Big Sur resolve these issues, but until then, short of redesigning these components (which is on the roadmap, and I have an issue for that: #19) there's not a lot I can do.

**Comment by ovanbiervliet** [comment]
After restarting, the first time I see the Pika window the icons look fine. But as soon as I interact, even trying to take a window screenshot with CleanShot, makes the icons go wrong. Interacting with the individual icons afterwards restores the correct colors again.

**Comment by superhighfives** [comment]
Understood. Keen to check out how it is in the newer versions of Big Sur, and I'm flagging it as part of #28 and #19. 👍 Going to close this in the meantime.
