### ISSUE TITLE
Show hex color below magnifier glass

### ISSUE THREAD

**Issue by CodeBrauer** [superhighfives/pika#66]
**Is your feature request related to a problem? Please describe.**
If I pick a color just to ensure, the color is the right one - I want to see the hex right away below the magnifier.
So I don't have to pick, paste somewhere to check the value.

**Describe the solution you'd like**
If I press my shortcut to pick a color, I want to see the hex value of the current color right away.

**Describe alternatives you've considered**
ColorSlurp and Sip use the same logic, but they switch to "PRO-features" with subscriptions. (See 

**Additional context**
-
<img width="215" alt="Bildschirmfoto 2021-05-31 um 15 13 12" src="https://user-images.githubusercontent.com/2059754/120198728-b964ce00-c222-11eb-977d-957dfe2de933.png">
<img width="282" alt="Bildschirmfoto 2021-05-31 um 15 13 44" src="https://user-images.githubusercontent.com/2059754/120198774-cc779e00-c222-11eb-9784-83b56dd344a3.png">

**Comment by superhighfives** [comment]
Hey @CodeBrauer—appreciate you opening this issue. Unfortunately, due to the limitations of the API that Pika uses, it's outside the scope of this app. I've got some more context on what is happening behind the scenes here: https://github.com/superhighfives/pika/issues/45#issuecomment-782846224

If someone has a clever way to achieve this that doesn't require screen recording privledges, I'd love to hear about it. 👍 

Thanks again for the suggestion!
